name: Projekt_pyth

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH key debug
        run: |
          echo "${{ secrets.SSH_KEY }}"

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: vps2.m89.pl
          username: debian
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          script: |
            cd /app/Projekt_python_Patryk_Majcherczyk
            git pull origin main
            docker compose up -d
